//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conector
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public int COD_PRODUCTO { get; set; }
        public string NOMBRE { get; set; }
        public decimal PRECIO { get; set; }
        public int STOCK { get; set; }
        public Nullable<int> NIT_PROVEEDOR { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
