//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conector
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class USUARIO
    {
        public int ID { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string CLAVE { get; set; }
        public Nullable<int> ID_ROL { get; set; }


        [JsonIgnore]
        public virtual ROLES ROLES { get; set; }
    }
}
